os: Visual Studio 2017

clone_depth: 100

cache:
  - C:\.hunter -> .appveyor.yml

install:
    - git submodule update --init --recursive

build_script:
    - md build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=cmake/polly/vs-15-2017-win64.cmake ..
    - cmake --build . --config Release
